namespace Reline.Compilation.Diagnostics;

/// <summary>
/// Represents a diagnostic generated by compilation.
/// </summary>
/// <param name="Level">The severity level of the diagnostic.</param>
/// <param name="Description">The description of the diagnostic.</param>
/// <param name="Location">The span in the source text of the diagnostic,
/// or <see langword="null"/> if the diagnostic does not have a specific location.</param>
public readonly record struct Diagnostic(
	DiagnosticLevel Level,
	string Description,
	TextSpan? Location
);
