namespace Reline.Compilation.Diagnostics;

/// <summary>
/// Represents a diagnostic generated by compilation.
/// </summary>
public readonly record struct Diagnostic {

	/// <summary>
	/// The <see cref="DiagnosticDescription"/> of the diagnostic.
	/// </summary>
	public DiagnosticDescription Description { get; }
	/// <summary>
	/// The span in the source text of the diagnostic,
	/// or <see langword="null"/> if the diagnostic does not have a specific location.
	/// </summary>
	public TextSpan? Location { get; }
	/// <summary>
	/// The formatted description of the diagnostic.
	/// </summary>
	public string FormattedDescription { get; } = "No description";



	/// <summary>
	/// Initializes a new <see cref="Diagnostic"/> instance.
	/// </summary>
	/// <param name="description">The description of the diagnostic.</param>
	/// <param name="location">The span of the diagnostic in the source text.</param>
	public Diagnostic(DiagnosticDescription description, TextSpan? location, params object?[] formatArgs) {
		Description = description;
		Location = location;
		FormattedDescription = Description.FormatDescription(formatArgs);
	}



	public override string ToString() {
		string locationString = Location is not null ? $"({Location}) " : "";
		return $"{locationString}{Description.ErrorCode}: {FormattedDescription}";
	}

}

public static class DiagnosticDescriptionExtensions {

	/// <summary>
	/// Formats a <see cref="DiagnosticDescription"/> into a <see cref="Diagnostic"/>.
	/// </summary>
	/// <param name="description">The <see cref="DiagnosticDescription"/> to format.</param>
	/// <param name="location">The span in the source text of the diagnostic.</param>
	/// <param name="formatArgs">The arguments to format the description with.</param>
	/// <returns>A new <see cref="Diagnostic"/> created from <paramref name="description"/>.</returns>
	public static Diagnostic ToDiagnostic(this DiagnosticDescription description, TextSpan? location, params object?[] formatArgs) =>
		new(description, location, formatArgs);
	/// <summary>
	/// Formats a <see cref="DiagnosticDescription"/> into a <see cref="Diagnostic"/>.
	/// </summary>
	/// <param name="description">The <see cref="DiagnosticDescription"/> to format.</param>
	/// <param name="formatArgs">The arguments to format the description with.</param>
	/// <returns>A new <see cref="Diagnostic"/> created from <paramref name="description"/>.</returns>
	public static Diagnostic ToDiagnostic(this DiagnosticDescription description, params object?[] formatArgs) =>
		new(description, null, formatArgs);

}
