using Reline.Compilation.Diagnostics;
using Reline.Compilation.Syntax;

namespace Reline.Compilation.Lexing;

/// <summary>
/// The result of a <see cref="Lexer"/>.
/// </summary>
/// <param name="Tokens">The lexed syntax tokens.</param>
/// <param name="Diagnostics">The diagnostics generated by the lexer.</param>
public readonly record struct LexResult(
	ImmutableArray<SyntaxToken> Tokens,
	ImmutableArray<Diagnostic> Diagnostics
) {

	/// <summary>
	/// Whether the result has any fatal errors.
	/// </summary>
	public bool HasErrors =>
		Diagnostics.Any(d => d.Level == DiagnosticLevel.Error);

}
